<?php

namespace CleDiscount\CatalogueBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getArticles($nombreParPage, $page, $categorie, $marque)
    {
        
        if ($page < 1) {
            throw new \InvalidArgumentException('La page demandée n\'existe pas');
        }
        
        if ($marque == 'tous') {
            $query = $this->createQueryBuilder('a')
                        ->where('a.categorie = :categorie')
                        ->setParameter('categorie', $categorie)
                        ->orderBy('a.prixParticulier', 'DESC')
                        ->getQuery();         
        }
        else {
            $query = $this->createQueryBuilder('a')
                        ->where('a.categorie = :categorie')
                        ->setParameter('categorie', $categorie)
                        ->andWhere('a.marque = :marque')
                        ->setParameter('marque', $marque)
                        ->orderBy('a.prixParticulier', 'DESC')
                        ->getQuery();   
        }
        
        // On définit l'article à partir duquel commencer la liste
        $query->setFirstResult(($page-1) * $nombreParPage)
        // Ainsi que le nombre d'articles à afficher
              ->setMaxResults($nombreParPage);

        return new Paginator($query);
      }
}
